controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# UTILISATEUR
app_creation_utilisateur:
    path:       /utilisateur
    controller: App\Controller\UtilisateurController::creationUtilisateur
    methods:    PUT