<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxXI7Ik\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxXI7Ik/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxXI7Ik.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxXI7Ik\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDxXI7Ik\App_KernelDevDebugContainer([
    'container.build_hash' => 'DxXI7Ik',
    'container.build_id' => 'fee93cf2',
    'container.build_time' => 1737391971,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxXI7Ik');
