<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYSIovVg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYSIovVg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYSIovVg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYSIovVg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYSIovVg\App_KernelDevDebugContainer([
    'container.build_hash' => 'YSIovVg',
    'container.build_id' => 'b03326a8',
    'container.build_time' => 1737415090,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYSIovVg');
