<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTEZej2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTEZej2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTEZej2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTEZej2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTEZej2\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTEZej2',
    'container.build_id' => '9793acfa',
    'container.build_time' => 1737462360,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTEZej2');
